version: '3.8'

services:
  postgres:
    container_name: postgres-bug-tracker
    image: postgres:15.2-bullseye
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  pg_data: